insert into product_type (type_name) values('ISSEYMIYAKE/三宅一生');
insert into product_type (type_name) values('IWC/万国');
insert into product_type (type_name) values('izzue/伊苏');
insert into product_type (type_name) values('ISABELMARANT/伊萨贝尔玛兰');
insert into product_type (type_name) values('IDo/我愿意');
insert into product_type (type_name) values('0711TBILISI/0711TBILISI');
insert into product_type (type_name) values('3D-GOLD/金至尊');
insert into product_type (type_name) values('3.1PhillipLim/31PhillipLim');
insert into product_type (type_name) values('IHNOMUHNIT/IHNOMUHNIT');
insert into product_type (type_name) values('Y-3/山本耀司');
insert into product_type (type_name) values('ZENITH/真力时');
insert into product_type (type_name) values('zippo/之宝');
insert into product_type (type_name) values('ZEPPELIN/齐博林');
insert into product_type (type_name) values('Waltham/华生');
insert into product_type (type_name) values('WEMPE/WEMPE');
insert into product_type (type_name) values('xiangxielishe/香榭丽奢');
insert into product_type (type_name) values('Wedgwood/豹害亚·璋敏活');
insert into product_type (type_name) values('VivienneWestwood/西太后');
insert into product_type (type_name) values('Wandler/万德勒');
insert into product_type (type_name) values('Vertu/威图');
insert into product_type (type_name) values('Vince/文斯');
insert into product_type (type_name) values('Viviennewestwood/薇薇安韦斯特伍德');
insert into product_type (type_name) values('VERSUS/范瑟丝');
insert into product_type (type_name) values('Valentino/华伦天奴');
insert into product_type (type_name) values('VacheronConstantin/江诗丹顿');
insert into product_type (type_name) values('VictoriaBeckham/维多利亚贝克汉姆');
insert into product_type (type_name) values('VETEMENTS/唯特萌');
insert into product_type (type_name) values('Valextra/瓦莱可斯特拉');
insert into product_type (type_name) values('Versace/范思哲');
insert into product_type (type_name) values('VancleefArpels/梵克雅宝');
insert into product_type (type_name) values('VERRI/VERRI');
insert into product_type (type_name) values('Nardin/雅典');
insert into product_type (type_name) values('U-BOAT/U-BOAT');
insert into product_type (type_name) values('UGG/UGG');
insert into product_type (type_name) values('TomFORd/汤姆福特');
insert into product_type (type_name) values('TISSOT/天梭');
insert into product_type (type_name) values('Tiffany&co/蒂芙尼');
insert into product_type (type_name) values('TIANWANG/天王');
insert into product_type (type_name) values('TUMI/途明/塔米');
insert into product_type (type_name) values('TODS/托德斯');
insert into product_type (type_name) values('ToryBurch/汤丽柏琦');
insert into product_type (type_name) values('Tudor/帝舵');
insert into product_type (type_name) values('TAGHeuer/泰格豪雅');
insert into product_type (type_name) values('ToscaBlu/ToscaBlu');
insert into product_type (type_name) values('TAVANNESWATCH/塔瓦内斯');
insert into product_type (type_name) values('TITONI/梅花表');
insert into product_type (type_name) values('TSL/谢瑞麟');
insert into product_type (type_name) values('ThierryMugler/穆勒');
insert into product_type (type_name) values('ThomBrowne/汤姆布朗');
insert into product_type (type_name) values('TommyHilfiger/汤米希尔费格');
insert into product_type (type_name) values('THENORTHFACE/北面');
insert into product_type (type_name) values('TEDBAKER/TEDBAKER');
insert into product_type (type_name) values('SWAROVSKI/施华洛世奇');
insert into product_type (type_name) values('Seagull/海鸥');
insert into product_type (type_name) values('SEIKO/精工');
insert into product_type (type_name) values('Supreme/萨普瑞密');
insert into product_type (type_name) values('Swatch/斯沃琪');
insert into product_type (type_name) values('SergioRossi/赛桥罗西');
insert into product_type (type_name) values('Samsonite/新秀丽');
insert into product_type (type_name) values('StefanoRicci/斯蒂芬劳尼治');
insert into product_type (type_name) values('stellaMcCartnev/斯特拉麦卡特尼');
insert into product_type (type_name) values('SaintLaurent/圣罗兰');
insert into product_type (type_name) values('StuartWeitzman/思提韦曼');
insert into product_type (type_name) values('Smythson/斯迈森');
insert into product_type (type_name) values('S.T.Dupont/法国都彭');
insert into product_type (type_name) values('St.John/盛蔷');
insert into product_type (type_name) values('SASS&BIDE/赛斯拜德');
insert into product_type (type_name) values('Samsoe&Samsoe/Samsoe&Samsoe');
insert into product_type (type_name) values('SelfPortrait/SelfPortrait');
insert into product_type (type_name) values('SCOTCH&SODA/苏格兰苏打');
insert into product_type (type_name) values('SCHAUMBURGWATCH/SCHAUMBURGWATCH');
insert into product_type (type_name) values('Stalvev/斯托尔维');
insert into product_type (type_name) values('sandro/桑德罗');
insert into product_type (type_name) values('Specialwomensclothing/特价女装');
insert into product_type (type_name) values('SeeBvChloe/SeeByChloe');
insert into product_type (type_name) values('sevenfriday/七个星期五');
insert into product_type (type_name) values('SophieHulme/索菲休姆');
insert into product_type (type_name) values('STAUD/STAUD');
insert into product_type (type_name) values('SNERKERS/SNERKERS');
insert into product_type (type_name) values('SCHAUMBURG/SCHAUMBURG');
insert into product_type (type_name) values('RaymondWeil/雷蒙威');
insert into product_type (type_name) values('RogerDubuis/罗杰杜彼');
insert into product_type (type_name) values('RomainJerome/罗曼哲罗姆');
insert into product_type (type_name) values('ROSSINL/罗西尼');
insert into product_type (type_name) values('RichardMille/里查德米尔');
insert into product_type (type_name) values('RobertoCavalli/罗伯特卡沃利');
insert into product_type (type_name) values('RADO/雷达');
insert into product_type (type_name) values('READYMADE/READYMADE');
insert into product_type (type_name) values('RIMOWA/日默瓦');
insert into product_type (type_name) values('Ray-Ban/雷朋');
insert into product_type (type_name) values('ReneCaovilla/芮妮乔薇拉');
insert into product_type (type_name) values('RogerVivier/罗杰维维亚');
insert into product_type (type_name) values('Rolex/劳力士');
insert into product_type (type_name) values('ROAMER/罗马');
insert into product_type (type_name) values('RACHELE拉凯莱/RACHELE拉凯莱');
insert into product_type (type_name) values('RobertadiCamerino/诺贝达');
insert into product_type (type_name) values('redline/红绳');
insert into product_type (type_name) values('ReFa/黎珐');
insert into product_type (type_name) values('REC/REC');
insert into product_type (type_name) values('RalphLauren/拉尔夫劳伦');
insert into product_type (type_name) values('Qeelin/麒麟');
insert into product_type (type_name) values('PierreKunz/皮埃尔.昆姿');
insert into product_type (type_name) values('PhillipLim/菲利林');
insert into product_type (type_name) values('Paulsmith/保罗史密斯');
insert into product_type (type_name) values('PoloRalphLauren/拉夫劳伦');
insert into product_type (type_name) values('Ports1961/宝姿1961');
insert into product_type (type_name) values('PINKO/品高');
insert into product_type (type_name) values('PhilippPlein/飞利浦普兰');
insert into product_type (type_name) values('PIAGET/伯爵');
insert into product_type (type_name) values('PATEKPHILIPPE/百达翡丽');
insert into product_type (type_name) values('PARMIGIANI/帕玛强尼');
insert into product_type (type_name) values('Panerai/沛纳海');
insert into product_type (type_name) values('PierreCardin/皮尔卡丹');
insert into product_type (type_name) values('PRADA/普拉达');
insert into product_type (type_name) values('PORSCHEDESIGN/保时捷设计');
insert into product_type (type_name) values('Pearl/珍珠');
insert into product_type (type_name) values('Pandora/潘多拉');
insert into product_type (type_name) values('ProenzaSchouler/PS');
insert into product_type (type_name) values('Police/Police');
insert into product_type (type_name) values('Other/其他');
insert into product_type (type_name) values('OFF-WHITE/OFF-WHITE');
insert into product_type (type_name) values('OAKLEY/欧克利');
insert into product_type (type_name) values('OMEGA/欧米茄');
insert into product_type (type_name) values('Oris/豪利时');
insert into product_type (type_name) values('NinaRicci/莲娜丽姿');
insert into product_type (type_name) values('Nomos/诺莫斯');
insert into product_type (type_name) values('N21/N21');
insert into product_type (type_name) values('NIVREL/尼芙尔');
insert into product_type (type_name) values('NeilBarrett/尼奥贝奈特');
insert into product_type (type_name) values('MESSIKA/梅西卡');
insert into product_type (type_name) values('MaisonMargiela/梅森·马吉拉');
insert into product_type (type_name) values('ManuAtelier/马努');
insert into product_type (type_name) values('Marni/玛尼');
insert into product_type (type_name) values('Mido/美度');
insert into product_type (type_name) values('MA害扳笆X&噘捌O/MAX&CO');
insert into product_type (type_name) values('MauriceLacroix/艾美');
insert into product_type (type_name) values('Movado/摩凡陀');
insert into product_type (type_name) values('Moncler/蒙口');
insert into product_type (type_name) values('Moynat/莫纳');
insert into product_type (type_name) values('MaxMara/麦丝玛拉');
insert into product_type (type_name) values('MSGM/MSGM');
insert into product_type (type_name) values('MichaelKors/迈克科尔斯');
insert into product_type (type_name) values('MarcJacobs/马克雅克布');
insert into product_type (type_name) values('Moschino/莫斯奇诺');
insert into product_type (type_name)  values('Montblanc/万宝龙');
insert into product_type (type_name)  values('Mulberry/迈宝瑞');
insert into product_type (type_name)  values('MINGR/明牌珠宝');
insert into product_type (type_name)  values('Monet/莫奈');
insert into product_type (type_name)  values('MCM/MCM');
insert into product_type (type_name)  values('MIUMIU/缪缪');
insert into product_type (type_name)  values('Mikimoto/御木本');
insert into product_type (type_name)  values('MARUMANRZ/马如曼RZ');
insert into product_type (type_name)  values('ManoloBlahnik/莫罗·伯拉尼克');
insert into product_type (type_name)  values('MarumanFigaro/马如曼');
insert into product_type (type_name)  values('Mr&Mrs/Mr&Mrs');
insert into product_type (type_name)  values('MAISONMARGIELA/梅森马吉拉');
insert into product_type (type_name)  values('MaxMara/麦丝玛拉');
insert into product_type (type_name)  values('MARCELOBURLON/马塞洛布隆');
insert into product_type (type_name)  values('MAGASCHONI/MAGASCHONI');
insert into product_type (type_name)  values('MAISONMICHEL/MAISONMICHEL');
insert into product_type (type_name)  values('MAJE/MAJE');
insert into product_type (type_name)  values('MANGANO/曼加洛');
insert into product_type (type_name)  values('Lemaire/勒梅尔');
insert into product_type (type_name)  values('LOVEMOSCHINO/爱莫斯基诺');
insert into product_type (type_name)  values('Lamborghini/兰博基尼');
insert into product_type (type_name)  values('Lozza/拉瓦萨');
insert into product_type (type_name)  values('LOEWE/罗意威');
insert into product_type (type_name)  values('LANCEL/兰姿');
insert into product_type (type_name)  values('LONGINES/浪琴');
insert into product_type (type_name)  values('LANVIN/浪凡');
insert into product_type (type_name)  values('Lids/立姿');
insert into product_type (type_name)  values('LAVARO/拉夫兰瑞');
insert into product_type (type_name)  values('LACO/朗坤');
insert into product_type (type_name)  values('LittleLiffner/LittleLiffner');
insert into product_type (type_name)  values('Leysen/莱绅通灵');
insert into product_type (type_name)  values('LukfookJewellerv/六福珠宝');
insert into product_type (type_name)  values('LaoFengXiang/老凤祥');
insert into product_type (type_name)  values('LAMER/海蓝之谜');
insert into product_type (type_name)  values('LIAsophia/LIAsophia');
insert into product_type (type_name)  values('LouisVuitton/路易威登');
insert into product_type (type_name)  values('LUCKY/LUCKY');
insert into product_type (type_name)  values('Lancome/兰蔑');
insert into product_type (type_name)  values('Kate.spade/凯特丝蓓');
insert into product_type (type_name)  values('KarenWalker/凯伦沃克');
insert into product_type (type_name)  values('LACOSTE/拉科斯特');
insert into product_type (type_name)  values('LONGCHAMP/珑骧');
insert into product_type (type_name)  values('KarlLagerfeld/卡尔.拉格斐');
insert into product_type (type_name)  values('KATANASTARDOM/KATANASTARDOM');
insert into product_type (type_name)  values('KDC/金伯利');
insert into product_type (type_name)  values('KENZO/高田贤三');
insert into product_type (type_name)  values('JBrand/JBrand');
insert into product_type (type_name)  values('JeanRichard/尚维沙');
insert into product_type (type_name)  values('JILSANDER/吉尔桑德');
insert into product_type (type_name)  values('J.Crew/J.Crew');
insert into product_type (type_name)  values('Jorya/卓雅');
insert into product_type (type_name)  values('Jaeger-LeCoultre/积家');
insert into product_type (type_name)  values('Juicycouture/橘滋');
insert into product_type (type_name)  values('Juvenia/尊黄');
insert into product_type (type_name)  values('JaquetDroz/雅克德罗');
insert into product_type (type_name)  values('JACOB&CO/捷克豹');
insert into product_type (type_name)  values('JRA/JRA');
insert into product_type (type_name)  values('JeanPaulGaultier/高提耶');
insert into product_type (type_name)  values('Jimmychoo/周仰杰');
insert into product_type (type_name)  values('J.W.Anderson/J.W.Anderson');
insert into product_type (type_name)  values('JOMALONE/祖玛珑');
insert into product_type (type_name)  values('JKJYIJKJY');
insert into product_type (type_name)  values('JUSTKRAKEN/JUSTKRAKEN');
insert into product_type (type_name)  values('Herno/河诺');
insert into product_type (type_name)  values('HERMES/爱马仕');
insert into product_type (type_name)  values('HUBLOT/宇舶');
insert into product_type (type_name)  values('HAMILTON/汉米尔顿');
insert into product_type (type_name)  values('Houseofhello/Houseofhello');
insert into product_type (type_name)  values('HUGOBOSS/雨果博斯');
insert into product_type (type_name)  values('HOGAN/HOGAN');
insert into product_type (type_name)  values('HANAEMORI/森英惠');
insert into product_type (type_name)  values('HarryWinston/海瑞温斯顿');
insert into product_type (type_name)  values('HEIDIDAUS/赫蒂');
insert into product_type (type_name)  values('houseofhallo/恶搞包');
insert into product_type (type_name)  values('G-STARRAW/G-STARRAW');
insert into product_type (type_name)  values('GeraldGenta/尊达');
insert into product_type (type_name)  values('GRAHAM/格林汉姆');
insert into product_type (type_name)  values('GRAFF/格拉夫');
insert into product_type (type_name)  values('GUCCI/古驰');
insert into product_type (type_name)  values('Girard-perregaux/芝柏');
insert into product_type (type_name)  values('Goyard/戈雅');
insert into product_type (type_name)  values('GlashutteOriginal/格拉苏蒂');
insert into product_type (type_name)  values('GEOX/健乐士');
insert into product_type (type_name)  values('GIVENCHY/纪梵希');
insert into product_type (type_name)  values('GEDEBE/GEDEBE');
insert into product_type (type_name)  values('GUESS/盖尔斯');
insert into product_type (type_name)  values('GreyAnt/灰蚂蚁');
insert into product_type (type_name)  values('GiuseppeZanotti/朱塞佩.萨诺蒂');
insert into product_type (type_name)  values('Girard-Perregaux/Girard-Perregaux');
insert into product_type (type_name)  values('GCDS/GCDS');
insert into product_type (type_name)  values('GAGA/GAGA');
insert into product_type (type_name)  values('GENTLEMONSTER/GM');
insert into product_type (type_name)  values('FOSSIL/FOSSIL');
insert into product_type (type_name)  values('FOX/FOX');
insert into product_type (type_name)  values('FearofGod/FearofGod');
insert into product_type (type_name)  values('FIYTA/飞亚达');
insert into product_type (type_name)  values('FranckMuller/法兰克穆勒');
insert into product_type (type_name)  values('FolliFollie/芙丽芙丽');
insert into product_type (type_name)  values('FrederiqueConstant/康斯登');
insert into product_type (type_name)  values('Ferragamo/菲拉格慕');
insert into product_type (type_name)  values('Furla/芙拉');
insert into product_type (type_name)  values('FION/菲安妮');
insert into product_type (type_name)  values('FENDI/芬迪');
insert into product_type (type_name)  values('Frankiemorello/Frankiemorello');
insert into product_type (type_name)  values('FAURELEPAGE/FAURELEPAGE');
insert into product_type (type_name)  values('Fred/斐登');
insert into product_type (type_name)  values('FORTIS/富利斯');
insert into product_type (type_name)  values('ErnestBorel/依波路');
insert into product_type (type_name)  values('EBOHR/依波');
insert into product_type (type_name)  values('Epos/爱宝时');
insert into product_type (type_name)  values('ECCO/爱步');
insert into product_type (type_name)  values('Emilechouriet/艾米龙');
insert into product_type (type_name)  values('ELYSEE/艾力舍');
insert into product_type (type_name)  values('ErmenegildoZegna/杰尼亚');
insert into product_type (type_name)  values('EmilioPucci/璞琪');
insert into product_type (type_name)  values('ELISABETTAFRANCHI/ELISABETTAFRANCHI');
insert into product_type (type_name)  values('ENICAR/英纳格');
insert into product_type (type_name)  values('Delvaux/德尔沃');
insert into product_type (type_name)  values('DKNY/唐可娜儿');
insert into product_type (type_name)  values('Dazzle/地素');
insert into product_type (type_name)  values('D.W/丹尼尔.惠灵顿');
insert into product_type (type_name)  values('Diesel/迪塞尔');
insert into product_type (type_name)  values('Davidoff/大卫·杜夫');
insert into product_type (type_name)  values('Dior/迪奥');
insert into product_type (type_name)  values('DOLCE&GABBANA/杜嘉班纳');
insert into product_type (type_name)  values('DeBeers/戴比尔斯');
insert into product_type (type_name)  values('DesignerShoes/设计师鞋');
insert into product_type (type_name)  values('DesignerOthers/设计师其他');
insert into product_type (type_name)  values('DIANEVONFURSTENBERG/黛安·冯·芙丝汀宝');
insert into product_type (type_name)  values('DesignerClothing/设计师服装');
insert into product_type (type_name)  values('DesignerBag/设计师包');
insert into product_type (type_name)  values('DONDUP/DONDUP');
insert into product_type (type_name)  values('DesignerJewelry/设计师珠宝');
insert into product_type (type_name)  values('DUVETICA/DUVETICA');
insert into product_type (type_name)  values('DEGAIA/迪嘉雅');
insert into product_type (type_name)  values('DILLO/迪洛');
insert into product_type (type_name)  values('Casio/卡西欧');
insert into product_type (type_name)  values('Certina/雪铁纳');
insert into product_type (type_name)  values('Citizen/西铁城');
insert into product_type (type_name)  values('Concord/君皇');
insert into product_type (type_name)  values('CODEX/豪度');
insert into product_type (type_name)  values('CanadaGoose/加拿大鹅');
insert into product_type (type_name)  values('Klein/CK');
insert into product_type (type_name)  values('ClubMonaco/ClubMonaco');
insert into product_type (type_name)  values('CarlFBucherer/宝齐莱');
insert into product_type (type_name)  values('CHIARAFERRAGNI/琪娅拉法拉格尼');
insert into product_type (type_name)  values('CORUM/昆仑');
insert into product_type (type_name)  values('Chopard/萧邦');
insert into product_type (type_name)  values('ChromeHearts/克罗心');
insert into product_type (type_name)  values('CHRONASWISS/瑞宝');
insert into product_type (type_name)  values('Chloe/蔻依');
insert into product_type (type_name)  values('Chanel/香奈儿');
insert into product_type (type_name)  values('COACH/蔻驰');
insert into product_type (type_name)  values('Chaumet/尚美');
insert into product_type (type_name)  values('CHARLES&KEITH/小ck');
insert into product_type (type_name)  values('Cartier/卡地亚');
insert into product_type (type_name)  values('Celine/瑟琳');
insert into product_type (type_name)  values('CHARRIOL/夏利豪');
insert into product_type (type_name)  values('CHJJEWELLERY/潮宏基');
insert into product_type (type_name)  values('CocoDeste/CocoDeste');
insert into product_type (type_name)  values('Coccinelle/可奇奈尔');
insert into product_type (type_name)  values('COMTESSE/COMTESSE');
insert into product_type (type_name)  values('ChowSangSang/周生生');
insert into product_type (type_name)  values('CHOWTaiSeng/周大生');
insert into product_type (type_name)  values('CommedesGarconsPlav/川久保玲书');
insert into product_type (type_name)  values('CCSKYEDesignerOriginal/CCSKYE设计师原创');
insert into product_type (type_name)  values('Cavalliclass/Cavalliclass');
insert into product_type (type_name)  values('ChristianLouboutin/克里斯提鲁布托');
insert into product_type (type_name)  values('CHAMPION/冠军');
insert into product_type (type_name)  values('ChowTaiFook/周大福');
insert into product_type (type_name)  values('BCBGMaxAzria/BCBGMaxAzria');
insert into product_type (type_name)  values('BALMAIN/巴尔曼');
insert into product_type (type_name)  values('Breitling/百年灵');
insert into product_type (type_name)  values('Bell&ross/柏莱士');
insert into product_type (type_name)  values('BALL/波尔');
insert into product_type (type_name)  values('Baume&mercier/名仕');
insert into product_type (type_name)  values('Blancpain/宝珀');
insert into product_type (type_name)  values('Breguet/宝玑');
insert into product_type (type_name)  values('Balenciaga/巴黎世家');
insert into product_type (type_name)  values('Burberry/博柏利');
insert into product_type (type_name)  values('BVLGARI/宝格丽');
insert into product_type (type_name)  values('BALLY/巴利');
insert into product_type (type_name)  values('BOTTEGAVENETA/葆蝶家');
insert into product_type (type_name)  values('Buccellati/布契拉提');
insert into product_type (type_name)  values('balco/拜戈');
insert into product_type (type_name)  values('BREE/BREE');
insert into product_type (type_name)  values('BearBrick/暴力熊');
insert into product_type (type_name)  values('BRISTON/布里');
insert into product_type (type_name)  values('BO栈允二导憨YIBOYY');
insert into product_type (type_name)  values('ByFar/ByFar');
insert into product_type (type_name)  values('Boucheron/宝诗龙');
insert into product_type (type_name)  values('Baccarat/巴卡拉');
insert into product_type (type_name)  values('BOYLONDON/BOYLONDON');
insert into product_type (type_name)  values('BABATON/BABATON');
insert into product_type (type_name)  values('BYWP/百德彼');
insert into product_type (type_name)  values('ARNOLD&SON/亚诺');
insert into product_type (type_name)  values('ASSCIASSC');
insert into product_type (type_name)  values('AMIRA/AMIRA');
insert into product_type (type_name)  values('A.P.C/A.P.C');
insert into product_type (type_name)  values('ARMANI/阿玛尼');
insert into product_type (type_name)  values('AudemarsPiguet/爱彼');
insert into product_type (type_name)  values('AlfredDunhill/登喜路');
insert into product_type (type_name)  values('ANYAHINDMARCH/安雅.希德玛芝');
insert into product_type (type_name)  values('APMMonaco/APM');
insert into product_type (type_name)  values('A.lange&sohne/朗格');
insert into product_type (type_name)  values('AlexanderMcQueen/亚历山大.麦昆');
insert into product_type (type_name)  values('AK/薇欧服饰');
insert into product_type (type_name)  values('AVON/雅芳');
insert into product_type (type_name)  values('AlexanderWang/亚历山大.王');
insert into product_type (type_name)  values('AcneStudios/艾克妮');
insert into product_type (type_name)  values('ANTEPRIMA/安蒂佩玛');
insert into product_type (type_name)  values('A.Testoni/铁狮东尼');
insert into product_type (type_name)  values('AmericaANCON/美国ANCON');
insert into product_type (type_name)  values('ABATHINGAPEIABATHINGAPE');
insert into product_type (type_name)  values('Anna/安娜');
insert into product_type (type_name)  values('ANGONA/ANGONA');
insert into product_type (type_name)  values('AMERICANEAGLE/美国鹰');
insert into product_type (type_name)  values('ACRONYMIACRONYM');
insert into product_type (type_name)  values('adidas/阿迪达斯');
insert into product_type (type_name)  values('ARCTERYX/始祖鸟');



INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(1, '箱包', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(2, '配饰', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(3, '配件', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(4, '手表', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(5, '钟表', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(6, '首饰', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(7, '鞋靴', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(8, '服饰', 0, 1);
INSERT INTO sxb.product_category (id, name, parent_id, status) VALUES(9, '其他', 0, 1);
insert into product_category (name,parent_id) VALUES('箱包-斜挎包',1);
insert into product_category (name,parent_id) VALUES('箱包-手提包',1);
insert into product_category (name,parent_id) VALUES('箱包-双肩包',1);
insert into product_category (name,parent_id) VALUES('箱包-公文包',1);
insert into product_category (name,parent_id) VALUES('箱包-化妆包/洗漱包 ',1);
insert into product_category (name,parent_id) VALUES('箱包-腰包/胸包',1);
insert into product_category (name,parent_id) VALUES('箱包-手包',1);
insert into product_category (name,parent_id) VALUES('箱包-钱包/卡包',1);
insert into product_category (name,parent_id) VALUES('箱包-钥匙包/证件套 ',1);
insert into product_category (name,parent_id) VALUES('箱包-旅行包/行李箱 ',1);
insert into product_category (name,parent_id) VALUES('箱包-其他',1);
insert into product_category (name,parent_id) VALUES('配饰-腰带/腰链',2);
insert into product_category (name,parent_id) VALUES('配饰-围巾/丝巾/方巾',2);
insert into product_category (name,parent_id) VALUES('配饰-帽子/头巾',2);
insert into product_category (name,parent_id) VALUES('配饰-手套',2);
insert into product_category (name,parent_id) VALUES('配饰-钥匙扣/挂件',2);
insert into product_category (name,parent_id) VALUES('配饰-领结/领带',2);
insert into product_category (name,parent_id) VALUES('配饰-墨镜/眼镜',2);
insert into product_category (name,parent_id) VALUES('配饰-丝巾扣/腰带扣 ',2);
insert into product_category (name,parent_id) VALUES('配饰-其他',2);
insert into product_category (name,parent_id) VALUES('配饰-美妆',2);
insert into product_category (name,parent_id) VALUES('配件-钢笔/签字笔等 ',3);
insert into product_category (name,parent_id) VALUES('配件-笔记本',3);
insert into product_category (name,parent_id) VALUES('配件-烟盒/眼镜盒',3);
insert into product_category (name,parent_id) VALUES('配件-笔袋/眼镜袋',3);
insert into product_category (name,parent_id) VALUES('配件-打火机',3);
insert into product_category (name,parent_id) VALUES('配件-其他',3);
insert into product_category (name,parent_id) VALUES('配件-手机链',3);
insert into product_category (name,parent_id) VALUES('配件-百货',3);
insert into product_category (name,parent_id) VALUES('配件-盒子/尘袋',3);
insert into product_category (name,parent_id) VALUES('配件-香水',3);
insert into product_category (name,parent_id) VALUES('配件-红酒',3);
insert into product_category (name,parent_id) VALUES('配件-瓷器',3);
insert into product_category (name,parent_id) VALUES('配件-雨伞',3);
insert into product_category (name,parent_id) VALUES('配件-球杆',3);
insert into product_category (name,parent_id) VALUES('手表-自动机械表 ',4);
insert into product_category (name,parent_id) VALUES('手表-手动机械表 ',4);
insert into product_category (name,parent_id) VALUES('手表-石英表',4);
insert into product_category (name,parent_id) VALUES('钟表-手表',5);
insert into product_category (name,parent_id) VALUES('钟表-名表',5);
insert into product_category (name,parent_id) VALUES('首饰-项链/吊坠',6);
insert into product_category (name,parent_id) VALUES('首饰-戒指/指环',6);
insert into product_category (name,parent_id) VALUES('首饰-耳环/耳钉/耳夹',6);
insert into product_category (name,parent_id) VALUES('首饰-手镯/手链/手环',6);
insert into product_category (name,parent_id) VALUES('首饰-胸针/袖扣/领带夹 ',6);
insert into product_category (name,parent_id) VALUES('首饰-发夹/发箍',6);
insert into product_category (name,parent_id) VALUES('首饰-其他',6);
insert into product_category (name,parent_id) VALUES('首饰-珠宝钻石 ',6);
insert into product_category (name,parent_id) VALUES('首饰-设计师珠宝 ',6);
insert into product_category (name,parent_id) VALUES('鞋靴-休闲鞋',7);
insert into product_category (name,parent_id) VALUES('鞋靴-运动鞋',7);
insert into product_category (name,parent_id) VALUES('鞋靴-高跟鞋',7);
insert into product_category (name,parent_id) VALUES('鞋靴-平跟鞋',7);
insert into product_category (name,parent_id) VALUES('鞋靴-凉鞋/拖鞋',7);
insert into product_category (name,parent_id) VALUES('鞋靴-靴子/雪地靴',7);
insert into product_category (name,parent_id) VALUES('鞋靴-其他',7);
insert into product_category (name,parent_id) VALUES('服饰-大衣/风衣',8);
insert into product_category (name,parent_id) VALUES('服饰-西服/西裤',8);
insert into product_category (name,parent_id) VALUES('服饰-皮衣/夹克',8);
insert into product_category (name,parent_id) VALUES('服饰-外套/卫衣',8);
insert into product_category (name,parent_id) VALUES('服饰-短裙/短裤',8);
insert into product_category (name,parent_id) VALUES('服饰-衬衫',8);
insert into product_category (name,parent_id) VALUES('服饰-T恤 ',8);
insert into product_category (name,parent_id) VALUES('服饰-牛仔裤',8);
insert into product_category (name,parent_id) VALUES('服饰-羽绒服',8);
insert into product_category (name,parent_id) VALUES('服饰-连衣裙',8);
insert into product_category (name,parent_id) VALUES('服饰-长裙/半身裙',8);
insert into product_category (name,parent_id) VALUES('服饰-皮草',8);
insert into product_category (name,parent_id) VALUES('服饰-上衣',8);
insert into product_category (name,parent_id) VALUES('服饰-套装',8);
insert into product_category (name,parent_id) VALUES('服饰-其他',8);
insert into product_category (name,parent_id) VALUES('服饰-服装',8);


insert into product_material (name) values ('植鞣革');
insert into product_material (name) values ('牛皮');
insert into product_material (name) values ('荔枝牛皮');
insert into product_material (name) values ('羊皮');
insert into product_material (name) values ('帆布');
insert into product_material (name) values ('牛仔帆布');
insert into product_material (name) values ('皮革漆皮');
insert into product_material (name) values ('EPI牛皮');
insert into product_material (name) values ('尼龙');
insert into product_material (name) values ('PVC');
insert into product_material (name) values ('毛呢');
insert into product_material (name) values ('丝绒');
insert into product_material (name) values ('织物');
insert into product_material (name) values ('复古油蜡皮');
insert into product_material (name) values ('鹿皮');
insert into product_material (name) values ('羊毛');
insert into product_material (name) values ('鳄鱼皮');
insert into product_material (name) values ('蜥蜴皮');
insert into product_material (name) values ('Epsom');
insert into product_material (name) values ('Swift');
insert into product_material (name) values ('Clemence');
insert into product_material (name) values ('Togo');
insert into product_material (name) values ('Evercolor');
insert into product_material (name) values ('Mysore');
insert into product_material (name) values ('Boxcalf');
insert into product_material (name) values ('Fjord');
insert into product_material (name) values ('BareniaNatural');
insert into product_material (name) values ('TaurillonNobillo');
insert into product_material (name) values ('Evercalf');
insert into product_material (name) values ('Sombrero');
insert into product_material (name) values ('Grizzly');
insert into product_material (name) values ('缎面');
insert into product_material (name) values ('Chamonix');
insert into product_material (name) values ('Sikkim');
insert into product_material (name) values ('Chevre');
insert into product_material (name) values ('Negonda');
insert into product_material (name) values ('Evergrain');
insert into product_material (name) values ('亚克力');
insert into product_material (name) values ('珍珠鱼皮');
insert into product_material (name) values ('蛇皮');
insert into product_material (name) values ('天鹅绒');
insert into product_material (name) values ('PU');
insert into product_material (name) values ('水晶皮');
insert into product_material (name) values ('鸵鸟皮毛');
insert into product_material (name) values ('珠光皮');
insert into product_material (name) values ('马毛');
insert into product_material (name) values ('亚麻');
insert into product_material (name) values ('灯芯绒');
insert into product_material (name) values ('绸缎');
insert into product_material (name) values ('树脂');
insert into product_material (name) values ('蚕丝');
insert into product_material (name) values ('塑料');
insert into product_material (name) values ('藤编');
insert into product_material (name) values ('亮片');
insert into product_material (name) values ('涤纶');
insert into product_material (name) values ('串珠');
insert into product_material (name) values ('水钻');
insert into product_material (name) values ('羽绒');
insert into product_material (name) values ('兔毛');
insert into product_material (name) values ('狐狸毛');
insert into product_material (name) values ('貂皮');
insert into product_material (name) values ('金属');
insert into product_material (name) values ('针织');
insert into product_material (name) values ('拉菲草');
insert into product_material (name) values ('橡胶');
insert into product_material (name) values ('竹节');
insert into product_material (name) values ('马皮(革);');
insert into product_material (name) values ('科技皮');
insert into product_material (name) values ('人造毛');
insert into product_material (name) values ('真丝');
insert into product_material (name) values ('聚酷纤维');
insert into product_material (name) values ('鹿皮');
insert into product_material (name) values ('猪皮');
insert into product_material (name) values ('其他');
insert into product_material (name) values ('18k黄金');
insert into product_material (name) values ('18k玫瑰金');
insert into product_material (name) values ('银');
insert into product_material (name) values ('黄金');
insert into product_material (name) values ('白金');
insert into product_material (name) values ('铂金');
insert into product_material (name) values ('18k白金');
insert into product_material (name) values ('合金');
insert into product_material (name) values ('钻石');
insert into product_material (name) values ('珍珠');
insert into product_material (name) values ('AG925');
insert into product_material (name) values ('Au750');
insert into product_material (name) values ('Au750');
insert into product_material (name) values ('Au750');
insert into product_material (name) values ('白金');
insert into product_material (name) values ('Au750');
insert into product_material (name) values ('玫瑰金');
insert into product_material (name) values ('Pt950');
insert into product_material (name) values ('陶瓷');
insert into product_material (name) values ('翡翠');
insert into product_material (name) values ('玛瑙');
insert into product_material (name) values ('14K');
insert into product_material (name) values ('14K金');
insert into product_material (name) values ('水晶');
insert into product_material (name) values ('祖母绿');
insert into product_material (name) values ('红宝石');
insert into product_material (name) values ('蓝宝石');
insert into product_material (name) values ('PT900');
insert into product_material (name) values ('孔雀石');
insert into product_material (name) values ('彩钻');
insert into product_material (name) values ('足金');
insert into product_material (name) values ('琥珀');
insert into product_material (name) values ('PT850');
insert into product_material (name) values ('镀金');
insert into product_material (name) values ('珊瑚');
insert into product_material (name) values ('欧珀');
insert into product_material (name) values ('9K');
insert into product_material (name) values ('10K');
insert into product_material (name) values ('750K金');
insert into product_material (name) values ('人造珍珠');
insert into product_material (name) values ('碧玺');
insert into product_material (name) values ('和田玉');
insert into product_material (name) values ('海蓝宝石');
insert into product_material (name) values ('玻璃');
insert into product_material (name) values ('木质');
insert into product_material (name) values ('蜜蜡');
insert into product_material (name) values ('不锈钢');
insert into product_material (name) values ('石榴');
insert into product_material (name) values ('石搪瓷');
